import React from 'react';
import './ExamDisplay.css';

const ExamDisplay = ({ examData, onGenerateNew }) => {
  const { topic, questionCount, questions, generatedAt } = examData;

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    const examContent = `
${topic.toUpperCase()} EXAM
Generated on: ${new Date(generatedAt).toLocaleDateString()}
Number of Questions: ${questionCount}

${questions.map((q, index) => `${index + 1}. ${q.question}\n\nAnswer: _______________\n\n`).join('')}

---
Generated by AI Exam Generator
    `.trim();

    const blob = new Blob([examContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${topic.toLowerCase().replace(/\s+/g, '-')}-exam.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  return (
    <div className="exam-display">
      <div className="exam-header no-print">
        <div className="exam-info">
          <div className="exam-icon">
            <i className="fas fa-file-text"></i>
          </div>
          <div className="exam-details">
            <h2>{topic} Exam</h2>
            <div className="exam-meta">
              
              <span className="meta-item">
                <i className="fas fa-list-ol"></i>
                {questionCount} Questions
              </span>
              <span className="meta-item">
                <i className="fas fa-calendar-alt"></i>
                {formatDate(generatedAt)}
              </span>
            </div>
          </div>
        </div>

        <div className="exam-actions">
          <button onClick={handlePrint} className="action-btn print-btn">
            <i className="fas fa-print"></i>
            Print Exam
          </button>
          <button onClick={handleDownload} className="action-btn download-btn">
            <i className="fas fa-download"></i>
            Download
          </button>
          <button onClick={onGenerateNew} className="action-btn new-exam-btn">
            <i className="fas fa-plus"></i>
            Generate New Exam
          </button>
        </div>
      </div>

      <div className="exam-paper ">
        <div className="paper-header">
          <h1 className="exam-title">{topic} Exam</h1>
          <div className="exam-info-print">
            <div className="info-row">
              <span>Name: ________________________</span>
              <span>Date: {formatDate(generatedAt)}</span>
            </div>
            <div className="info-row">
              <span>Class: ________________________</span>
              <span>Time: _______ minutes</span>
            </div>
          </div>
          <div className="instructions">
            <h3>Instructions:</h3>
            <ul>
              <li>Read each question carefully</li>
              <li>Show your work where applicable</li>
              <li>Write your answers clearly</li>
              <li>Check your answers when finished</li>
            </ul>
          </div>
        </div>

        <div className="questions-section">
          <h3>Questions ({questionCount} questions)</h3>
          {questions.map((question, index) => (
            <div key={question.id} className="question-item">
              <div className="question-number">{index + 1}.</div>
              <div className="question-content">
                <p className="question-text">{question.question}</p>
                <div className="answer-space">
                  <span className="answer-label">Answer: </span>
                  <div className="answer-line"></div>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="exam-footer">
          <div className="footer-content">
            <p>Generated by AI Exam Generator</p>
            <p>© 2025 - Created for Educational Use</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ExamDisplay;